name: Release Build
env:
  CI: true
  BUILD_VERSION: 'v6.0.8-alpha' # TODO: Get from release tag.
  PUBLISH: false

# Run when release is created on GitHub
on:
  push:
    branches:
      #      - 'dev/*'
      - 'feature/nightly-actions'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - uses: actions/upload-artifact@v3
        with:
          name: release-build
          path: build/libs/*.jar

      - name: Publish to CurseForge and Modrinth
        uses: gradle/gradle-build-action@v2
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
          arguments: publishMod

      # TODO: Publish to maven.