name: Release Build
env:
  CI: true
  BUILD_VERSION: ${{ github.event.release.tag_name }}
  CHANGELOG: ${{ github.event.release.body }}
  PUBLISH: false

# Run when release is created on GitHub
on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - uses: actions/upload-artifact@v3
        with:
          name: release-build
          path: build/libs/*.jar

      - name: Publish to CurseForge and Modrinth
        uses: gradle/gradle-build-action@v2
        env:
          CURSEFORGE_TOKEN: ${{ secrets.TOKEN_CURSEFORGE }}
          MODRINTH_TOKEN: ${{ secrets.TOKEN_MODRINTH }}
        with:
          arguments: publishMod

      # TODO: Publish to maven.

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          files: build/libs/*.jar